language: python

python:
  - '3.4'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls


script:
  - python test_fast_food.py
  - pytest --cov=.
  - pytest


after_success:
  - coveralls