language: python

python:
  -'3.4'
  -'3.5'
  -'3.6'

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage

scripts:
  - pytest test_fastfood.py


after_success:
  - coveralls